#! /bin/bash

require base

usage() {
  echo "Edit the taskrc for a given task"
  echo ""
  echo "dev edit [-h] {task}"
  echo "  {task} - the task to edit"
  echo ""
  echo "  -h: this message"
  exit 1
}

while getopts "h" OPT
do
  case OPT in
    h) usage ;;
  esac
done
shift $((OPTIND - 1))

# make sure we have the right number of args
test $# -gt 1 && usage
if test $# -eq 0; then
    if test -z "$DEV_TASK"; then
        die "No current task"
    fi
    task="$DEV_TASK"
else
    task=$1
fi

test "$EDITOR" != "" || die "\$EDITOR is not defined"

# get the arguments settled
sanity_check_task "$task"
task_exists "$task" || die "Task '$task' does not exist"

# finally, edit it
$EDITOR "$DEV_TASKS_DIR/$task.dev"
