#! /bin/bash

require base

usage() {
  echo "List all tasks in this project"
  echo ""
  echo "dev tasks [-h]"
  echo ""
  echo "  -h: this message"
  echo "  -1: list tasks in a single column"
  exit 1
}

SINGLE_COLUMN=false
while getopts "h1" OPT
do
  case $OPT in
    h) usage ;;
    1) SINGLE_COLUMN=true ;;
  esac
done
shift $((OPTIND - 1))

enumerate_tasks() {
  for pathname in $DEV_TASKS_DIR/*.dev; do
    test -e "$pathname" && $BASENAME $pathname | sed -e 's/\.dev$//'
  done
}

if $SINGLE_COLUMN; then
    enumerate_tasks
else
    enumerate_tasks | $SORT | $COLUMN | $COLUMN -t | $SED -e $'s/^/\t/'
fi
