#! /bin/bash

require base

usage() {
  echo "Create a new, blank task"
  echo ""
  echo "dev new [-h] {task} [{sources}]"
  echo "  {task} the name of the task to create"
  echo "  {souces} value of SOURCES for the task"
  echo ""
  echo "  -h: this message"
  exit 1
}

while getopts "h" OPT
do
  case $OPT in
    h) usage ;;
  esac
done
shift $((OPTIND - 1))

# make sure we have a task to load
test $# -ge 1 || die "No task specified"

# get the full path of the task
task="$1"; shift

sanity_check_task "$task" || die "Invalid task name '$task'"
task_exists "$task" && die "Task '$task' already exists"

test -d $DEV_TASKS_DIR || $MKDIR -p "$DEV_TASKS_DIR" || die "Cannot create $DEV_TASKS_DIR"

# everything looks good; let's set it up
task_file="$DEV_TASKS_DIR/$task.dev"

cat > "$task_file" <<EOF
SOURCES="$@"
EOF
