#! /bin/bash

usage() {
  echo "List all tasks in this project"
  echo ""
  echo "dev tasks [-h]"
  echo ""
  echo "  -h: this message"
  exit 1
}

while getopts "h" OPT
do
  case $OPT in
    h) usage ;;
  esac
done
shift $((OPTIND - 1))

# echo the available tasks in a nice columnar format
( for pathname in $DEV_TASKS_DIR/*
  do
    filename=`$BASENAME $pathname`
    echo $filename
  done
) | $SORT | $COLUMN | $COLUMN -t | $SED -e $'s/^/\t/'
