#! /bin/bash

require base

usage() {
    cat <<EOF
Show Dev variables
dev var -- display all variables (similar to 'env')
dev var -h -- this message
dev var list -- list all variable names
dev var <varname> -- display the value of <varname>
EOF
    exit 1
}

show_var() {
    eval "echo $1=\'\$$1\'"
}

interesting_variables="DEV_PROJECT_DIR"
interesting_variables="$interesting_variables DEV_TASKTYPE DEV_TASK_DIR"
interesting_variables="$interesting_variables DEV_TASKTYPES_DIR DEV_SUBCOMMANDS_PATH"
interesting_variables="$interesting_variables DEV_LOADER_PATH"
interesting_variables="$interesting_variables $dev_interesting_extension_variables"

if test $# -eq 0; then
    for var in $interesting_variables; do
        show_var $var
    done
    exit 0
fi

subsubcommand="$1"
shift
case "$subsubcommand" in
    list)
        for var in $interesting_variables; do
            echo $var
        done
        ;;
    -h) usage ;;
    *)
        eval "echo \"x\$$subsubcommand\" | sed -e s/^x//"
        ;;
esac
