#! /bin/bash

require base

usage() {
  echo "Clone an existing task"
  echo ""
  echo "dev clone [-h] {existing} {new}"
  echo "  {existing} - the task to clone"
  echo "  {new} - the new task to create"
  echo ""
  echo "  -h: this message"
  exit 1
}

while getopts "h" OPT
do
  case OPT in
    h) usage ;;
  esac
done
shift $((OPTIND - 1))

# make sure we have the right number of args
test $# -lt 2 && usage

# get the arguments settled
EXISTING=$1
sanity_check_task "$EXISTING"
task_exists "$EXISTING" || die "Task $EXISTING does not exist"

NEW=$2
sanity_check_task "$NEW"
task_exists "$NEW" && die "Task $NEW already exists"

cp -r $DEV_TASKS_DIR/$EXISTING $DEV_TASKS_DIR/$NEW

# helpfully remove any version-tracking stuff that might be in there
rm -rf $DEV_TASKS_DIR/$NEW/{.svn,CVS}
