#! /bin/bash

require base

usage() {
  echo "Edit the taskrc for a given task"
  echo ""
  echo "dev edit [-h] {task}"
  echo "  {task} - the task to edit"
  echo ""
  echo "  -h: this message"
  exit 1
}

while getopts "h" OPT
do
  case OPT in
    h) usage ;;
  esac
done
shift $((OPTIND - 1))

# make sure we have the right number of args
[ $# -ne 1 ] && usage

[ "$EDITOR" != "" ] || die "\$EDITOR is not defined"

# get the arguments settled
task=$1
sanity_check_task "$task"
task_exists "$task" || die "Task '$task' does not exist"

# finally, edit it
$EDITOR "`task_to_config_path $task`/taskrc"
