#! /bin/bash

usage() {
  echo "Delete a given task"
  echo ""
  echo "dev delete [-h] {task}"
  echo "  {task} the task to load"
  echo ""
  echo "  -h: this message"
  exit 1
}

while getopts "h" OPT
do
  case $OPT in
    h) usage ;;
  esac
done
shift $((OPTIND - 1))

# make sure we have a task to load
[ $# = 0 ] && usage

# get the full path of the task
task="$1"
sanity_check_task $task
task_path=`task_path "$task"`

[ -e $task_path -a -d $task_path ] || die "'$task' does not exist"

# don't delete the loaded task!
wip_is_loaded && [ `loaded_task` = "$task" ] && die "$task is currently loaded -- cannot delete"

warning_countdown "deleting '$task_path'"
$RM -rf $task_path
